export enum Subtypes {
    Break = "BREAK",
    Baby = "Baby",
    Basic = "Basic",
    EX = "EX",
    GX = "GX",
    GoldenrodGameCorner = "Goldenrod Game Corner",
    Item = "Item",
    Legend = "LEGEND",
    LevelUp = "Level-Up",
    Mega = "MEGA",
    PokemonTool = "Pokemon Tool",
    PokemonToolF = "Pokemon Tool F",
    Restored = "Restored",
    RocketsSecretMachine = "Rocket's Secret Machine",
    Special = "Special",
    Stadium = "Stadium",
    StageOne = "Stage 1",
    StageTwo = "Stage 2",
    Supporter = "Supporter",
    TagTeam = "TAG TEAM",
    TechnicalMachine = "Technical Machine",
    V = "V",
    VMax = "VMAX"
}